### ISSUE TITLE
What are your thoughts on .NET and CLR?

### ISSUE THREAD

**Issue by shpsec-dennis** [ariya/ama#10]
Hi Ariya,

What are your thoughts on .NET and CLR and how it relates to Java or other languages and "paradigms."

**Comment by ariya** [comment]
.NET has some amazing technologies. In the past, it wasn't widely adopted because it _officially_ ran only on Microsoft Windows. That's why I'm totally behind [.NET Foundation](http://www.dotnetfoundation.org/)'s initiative to:
- **open-source** many [important parts](http://www.dotnetfoundation.org/projects) of .NET framework ([C# 
  compiler](https://github.com/dotnet/roslyn), [CoreCLR](https://github.com/dotnet/coreCLR), [CoreFX](https://github.com/dotnet/corefx),  etc)
- make them **officially supported** on other platforms, including OS X and Linux.

_Side note_: Portions of CoreCLR are being utilized in [ChakraCore](https://github.com/Microsoft/ChakraCore) to assist its [porting](http://ariya.ofilabs.com/2016/01/playing-with-chakracore-on-linux.html) to non-Windows OS.

As a programming environment, the combination of C# and .NET are quite advanced, mature, and yet familiar enough to those who know Java (whether coming from enterprise application background or Android development shops). Some of us, who are getting more and more disappointed with the progress of Java 9/10/11 and/or the lack of Oracle's serious focus on Java on ARM, will move from just playing with C#/.NET on the side to considering it as a **mandatory tool** in our utility belt.

If I am allowed to make a _bold_ prediction, there will be a time in some near future where C#/.NET will eat Java's lunch in places where Java is still the king.

Thank you @shpsec-dennis!
