### ISSUE TITLE
What has changed from bieng a webkit commiter to a VP of a big company?

### ISSUE THREAD

**Issue by JoseVigil** [ariya/ama#17]

**Comment by ariya** [comment]
For a start, [Shape Security](https://www.crunchbase.com/organization/shape-security) is **not** a big company. I leave it as an exercise to the reader to estimate the number of employees we have right now :smirk: 

Also, being a contributor to a certain project, it's a matter of _label_. In theory, there is nothing stopping me from coming up with a patch to fix a WebKit bug and contributing it. In practice, this is not happening due to my lack of spare time and nothing to my role with Shape Security.

Thank you @JoseVigil!

**Comment by JoseVigil** [comment]
Hi Ariya,

Appreciate the answer, I would love to engage with you when you can find a spare time to keep the contact. 

Congratulations for your career. 

Thanks!
Jose
