### ISSUE TITLE
What prompted your transition out of your area of academic study: photonic systems?

### ISSUE THREAD

**Issue by newworldorder** [ariya/ama#21]

**Comment by ariya** [comment]
A physicist usually has the best interest to learn and understand advanced math, primarily to serve as a tool to solve complex physics problems. In fact, we often see a healthy collaboration between a physicist and their mathematician friend. Most physicists will not turn themselves into a full-time mathematician. However, once a while there will be a physicist who thinks, "Hmm, math is not so bad after all", and then decides to purse a career in the wonderful world of math.

What prompted my transition out of my area of academic study? It started as an **experiment**. Turned out that it is not so bad after all, so I stick with it.

In my answer to question #2 (_When did you start coding?_), I mentioned how I got interested in analog/digital micro-electronics when I was still very young. Back then, as I witnessed how digital computers became more powerful every year, I decided that I have to be good as mastering computers, hence the beginning of all side projects related to programming.

Meanwhile, what I studied at school was mostly a good mixture of physics, math, and micro-electronics. Starting with Engineering Physics major during my graduate, I ended up focusing on modern, complex photonics system as my postgraduate research. Throughout this time, I quickly realized that it is important to have a solid foundation in two very important areas: **math** and **software**. The former can be a story for some other time. For the latter, I discovered that I could learn all I need to know about software development by reading a lot of books (see #8) and contributing to FOSS projects.

I had some fun with Linux (see #3, _What was your best programming moment?_). It came with KDE as the desktop environment and thus, I learned about KDE as well. Before I knew, I became a regular [KDE contributor](https://behindkde.org/ariya-hidayat), mostly for its office suite. This activity helped me to understand software engineering, despite the fact that I never formally studied Computer Science.

By the time I [completed](http://ariya.ofilabs.com/2008/11/world-fastest-optical-polarization-tracking.html) my postgraduate research (curious? read this [8-page paper](https://www.osapublishing.org/oe/abstract.cfm?uri=oe-16-23-18984)), I had to make a choice. Should I stay in the academic world based on the research work I have done in the last few years? Or should I leverage my new profound interest and growing knowledge of software development to embrace a career as a software engineer? After a brief soul-searching period, I decided that I needed to **experiment** with something new because "If this software thing does not work out, I can always go back to university and teach". That was the **transition moment**.

Through my KDE involvement, I accumulated enough knowledge of Qt so that I could work for its maker, Trolltech. As I wrote in #12 (_When did you started coding?_), one thing led to another and here I am being comfortable working in the software industry!

**Comment by newworldorder** [comment]
Thanks for the rich response--lots of insights there.

**Comment by ariya** [comment]
Thanks for the intriguing question @newworldorder!

**Comment by diorahman** [comment]
Nice!
