### ISSUE TITLE
How do you perform valuation of web-apps or mobile-apps products?

### ISSUE THREAD

**Issue by edwinyudayana** [ariya/ama#24]
What's really inside of a "lines-of-code to USD" converter ? :v: 
Thank You. :laughing:

**Comment by ariya** [comment]
This is tough since I don't necessarily have the best business acumen nor marketing skills. But if I have to do it, then I will look at these two important aspects:
- **Quantitative attributes.** How many people are using the app actively? What is the current user growth? What is the most recent net promoter score?
- **Qualitative attributes.** Will it create a new market? Does it solve a real problem? What values does it bring to the happy users?

Thank you @edwinyudayana!
