### ISSUE TITLE
What is your top 10 computer science / software engineering books that every software engineer should read ?

### ISSUE THREAD

**Issue by dnkolegov** [ariya/ama#26]

**Comment by ariya** [comment]
Hi @dnkolegov,

It's hard for me to formulate such a list since my understanding of software development came from a practical experience (I didn't study Computer Science). See my answer to question #21 (_What prompted your transition out of your area of academic study?_) for more details. Yet, if you are an aspiring software engineer and you want to push your career to the next level, here is the list of **non-engineering books** which I highly recommend.

Find some inspirations:
- [Masters of Doom](http://www.goodreads.com/book/show/222146.Masters_of_Doom) (David Kushner)
- [Coders at Work](http://www.goodreads.com/book/show/6713575-coders-at-work) (Peter Seibel)

Organize yourself, be super-productive:
- [The 7 Habits of Highly Effective People](http://www.goodreads.com/book/show/36072.The_7_Habits_of_Highly_Effective_People) (Stephen Covey)
- [Gettings Things Done](https://www.goodreads.com/book/show/1633.Getting_Things_Done) (David Allen)
- [Thinking, Fast and Slow](http://www.goodreads.com/book/show/11468377-thinking-fast-and-slow) (Daniel Kahneman)

Understand people you work with:
- [Drive](http://www.goodreads.com/book/show/6452796-drive) (Daniel Pink)
- [Beyond Office Politics](http://www.goodreads.com/book/show/15840574-beyond-office-politics) (Linda Sommer)

Communicate like a pro:
- [The Elements of Style](http://www.goodreads.com/book/show/33514.The_Elements_of_Style) (Strunk & White)
- [The New Articulate Executive](http://www.goodreads.com/book/show/18918264-the-new-articulate-executive) (Granville Toogood)
- [Starts with Why](https://www.goodreads.com/book/show/7108725-start-with-why) (Simon Sinek)

I hope this list will be helpful!

**Comment by dnkolegov** [comment]
Great. Thanks!
