### ISSUE TITLE
Kisah Hidup Setelah Kuliah

### ISSUE THREAD

**Issue by nmfzone** [ariya/ama#35]
Selamat Siang Om Ariya.

Tolong ceritakan masa-masa setelah lulus kuliah dong. Masa-masa sebelum akhirnya terbang ke belahan dunia lain.

Thanks

**Comment by ariya** [comment]
Since this AMA is for the global audience, unfortunately I have to write my response in English.

I wish the questions would have been more specific.

For a quick summary of what I have been doing, [my LinkedIn profile](https://linkedin.com/in/ariyahidayat) is likely more than sufficient. For various stories during that time, sadly it has to wait until one day I have the time to sit down and write a biography.
