### ISSUE TITLE
How do you think we could do open source better?

### ISSUE THREAD

**Issue by sindresorhus** [ariya/ama#6]

**Comment by ariya** [comment]
A set of powerful tools available to the latest generation, everything from distributed VCS to the emerging programming language/environment, triggered this Cambrian explosion of all kinds of libraries, frameworks, and applications. This will continue for a while, but I believe we are ready to move to the next level of our maturity and responsibility.

There was a time when everyone and their uncle built their own JavaScript unit testing library. These days, only a handful of them are still being maintained and popularly used. This is because at any point in time, it is always cool and exciting to create something new. But then, the novelty wears off pretty quickly and the reality kicks in: it is boring and tedious to maintain a project.

Our new set of tools level the playing field. This is the virtual land of opportunity. The path from having an idea, making it available to the world, and potentially getting your 15 seconds of fame could not be easier. But there lies the danger. What if we also get bored easily? What if we can't afford a long trail to an important project that requires endurance and perseverance?

We tend to glorify a new framework, a fresh paradigm, a different perspective. We share them in various places, the weekly newsletter, Hacker News, Twitter, Reddit, what have you. A balance is long overdue. Every time projects such as cURL, SQLite, gzip, rsync, and many others is getting older, we shall cheer for them. It is time to start promoting battle-hardened projects, learning from their ups and downs, and adopting the values.

Maintainers are the true unsung heros of FOSS. They deserve our highest respect!

**Comment by sindresorhus** [comment]
:+1: Great answer. Thank you.

## 

> There was a time when everyone and their uncle built their own JavaScript unit testing library.

Ouch, https://github.com/sindresorhus/ava 😝
