### ISSUE TITLE
How do you relax?

### ISSUE THREAD

**Issue by sindresorhus** [ariya/ama#8]

**Comment by developit** [comment]
Was going to ask this

**Comment by ariya** [comment]
I discover some techniques that work for me. I'll write an answer for each one.

**Comment by ariya** [comment]
#### Sport

Although I'm not physically strong and I'm not good at sports, I still enjoy it as it can dramatically reduces my stress level. Sometimes it's about a few sets of badminton. Other times, it's a matter of practicing some basketball moves (behind the back layup has been my favorite since high school).

**Comment by ariya** [comment]
### Weekend trips

My kids inherit something from their parents: they're so silly! It's amazing how much fun and relaxing it is to spend the weekend doing things such as:
- learning the wonderful marine world at the Monterey Bay Aquarium
- going to a beach around Half Moon Bay, Santa Cruz, Aptos, Capitola, ...
- snow-sledding (I can't ski) somewhere around Tahoe
- camping and hiking, tons of great places around the Bay Area

**Comment by ariya** [comment]
### Reading

I've been fascinated by books as early as I could read. For me, reading always triggers my imagination, teleporting myself to a completely different world. I always feel different after reading any book, whether it's fiction or non-fiction. Most of time, it helps replenishing my source of joy, excitement, and inspiration.
